# path to directory containing the GOSAT files
GOSAT_dir: '/work/bb1170/RUN/b383736/data/GOSAT/GOSAT_till_2023/RemoTeCv241_2009-202308_final_daily/'
RemoTeC_version: '2.4.1'  # select RemoTeC_version, 2.4.0 or 2.4.1

# region for which GOSAT measurements should be used
# gosat_region=[20,48,-126,-70]       # lat_min, lat_max, lon_min, lon_max

Lat_min: 12
Lat_max: 56
Long_min: -134
Long_max: -62

# optional
# output directory for gosat.csv files, if None, will be placed in GOSAT_dir
outdir: '/work/bb1170/RUN/b383736/data/Flexpart_2021/measurements/RemoTeC/'
startdate:  20201001  # start date in format: yyyymmdd
enddate:    20220331  # end date in format: yyyymmdd
