# Config for script to automate conversion of ERA5 spectral files (into flex_extract download files )

# Start date in format yyyymmdd.
startdate: '20200901'
# Stop date in format yyyymmdd.
stopdate: '20221001'
# Path to output folder
outpath: //work/bb1170/RUN/b382762/data/Metview_test/240729/
# time resolution '1H', '1D', '1M', 'IV' 
timeres: '1M'
# spatial resolution as float
res: 1.
# borders as list: lat_min, long_min, lat_max, long_max
borders: [0, -120, 40, -100]

# optional:
# list of parameters that should be downloaded
param_list: [130,131]
data_type:        # an = analysis, fc = forecast
data_level:  ml       # sf = surface, ml = model levels, pl = pressure levels
flex_extract: False # set to true to download flex_extract files
# Flex_extract file name(s) which should be created, if none provided all flex_extract files will be created
fe_files: 
# ID for this run in format XXX, needed if the script is run multiple times in parallel
idnum:
